name: Strapi Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Git Pull 
        run: git pull

      - name: Install Dependencies
        run: npm install
        
      - name: Change Directory
        run: cd /home/ubuntu/my-strapi-project

      - name: Build Strapi
        run: npm run build

      - name: Run Strapi
        run: npm run develop
