name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.AWS_EC2_KEY }}
            HOSTNAME: ${{secrets.AWS_EC2_HOST}}
            USER_NAME: ${{secrets.AWS_EC2_USER}}
      
        run: |
          echo "$AWS_EC2_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_EC2_USER}@${AWS_EC2_HOST} '

              # Now we have got the access of EC2 and we will start the deploy .
              echo hello
              '
