name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: .github/infra
        run: terraform init

      - name: Import Existing EC2 Instance
        working-directory: .github/infra
        run: terraform import aws_instance.strapi-server i-04a6b0fc4736ceceb || echo "Instance already imported"

      - name: Terraform Plan
        working-directory: .github/infra
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: .github/infra
        run: terraform apply -auto-approve tfplan