name: Deloy to EC2

on:
  push:
    branches: [ "main" ]

jobs:

  build:


    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set working directory
      working-directory: /home/ubuntu/Task-18-6-24/my-strapi-project
    - name: Pull latest version
      run: git pull
    - name: Run App
      run: npm run develop

