name: Deloy to EC2

on:
  push:
    branches: [ "main" ]

jobs:

  build:


    runs-on: self-hosted

    steps:
    - name: Change Directory
      run: cd && cd Task-18-6-24/my-strapi-project
    - name: Pull latest version
      run: git pull https://github.com/sharqX/my-strapi-project.git
    - name: Run App
      run: npm run develop
