name: Deloy to EC2

on:
  push:
    branches: [ "main" ]

jobs:

    runs-on: self-hosted

  steps:
    - uses: actions/checkout@v1
    - name: Setup and run tests
      working-directory: home/ubuntu/Task-18-6-24/my-strapi-project
      run: |
        git pull
        npm run develop
