name: Deloy to EC2

on:
  push:
    branches: [ "main" ]

jobs:

  build:


    runs-on: self-hosted

    steps:
    - name: Show directory
      run: pwd
    - name: Pull latest version
      run: git pull 
    - name: Run App
      run: npm run develop

